export const NAVIGATION_ROUTES = {
  LOGIN: 'LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ENTER_CLASS: 'ENTER_CLASS',
  HOME: 'HOME',
  SPLASH:'SPLASH',
  GET_STARTED:'GET_STARTED',
  FORGET_PASSWORD:'FORGET_PASSWORD'
};
