export const NAVIGATION_ROUTES = {
  LOGIN: 'LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ENTER_CLASS: 'ENTER_CLASS',
  HOME: 'HOME',
  TABS: 'TABS',
  SPLASH: 'SPLASH',
  GET_STARTED: 'GET_STARTED',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  VITAL_HISTORY: 'VITAL_HISTORY',
  PROFILE:'PROFILE',
  NOTIFICATION:'NOTIFICATION',
  PRESCRIPTION:'PRESCRIPTION'

};
